import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import SidebarNav from "@/components/layout/SidebarNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Navbar>
          <img src="/img/100-bk-logo.png" alt="" />
        </Navbar>
        <SidebarNav className="z-10" />
        {children}
      </body>
    </html>
  );
}
